steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/image
  - --dockerfile=dockerfile/Dockerfile
  - --cache=true
  - --cache-ttl=1h
