ersion: "2"
networks:
  dev-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
services:
  redis:
    image: tuffylin/redis:3.2.12
    ports:
      - 6379:6379
    volumes:
      - /opt/redis_data:/data
    networks:
      dev-net:
        ipv4_address: 10.10.10.2
    container_name: "redis"
