apiVersion: v1
kind: Service
metadata:
  labels:
    app: lab01
  name: lab01-service
spec:
  ports:
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: lab01
  type: LoadBalancer
