apiVersion: v1
kind: Service
metadata:
  labels:
    app: lab01
  name: lab01-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  selector:
    app: lab01
  type: LoadBalancer
